services:
  - name: automated-meeting-agent
    type: web
    env: python
    plan: free
    buildCommand: "cd backend && poetry install"
    startCommand: "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9